name: sdk_fivetran

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v5
      - name: set-up python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
      - name: ejecutando connector.py
        run: python tutorials/pokemon_not_paginated/connector.py
    
